### PR TITLE
Added sample for automatic updater

### PR DESCRIPTION
**Pull request by msfjarvis**
This link is pretty much static, plus should be more updated than AFH (If you're as lazy as me ;) .

This will download the stuff, but you'll have to figure out the rest, or maybe I can do it sometime.

### CODE REVIEW

**Comment by msfjarvis** [comment]
Finally made this complete, will test this in an hour, and inform you.

**Comment by thewisenerd** [comment]
add a check for wget return value.

user might have no internet / download might fail.

add appropriate error message too.

**Comment by msfjarvis** [comment]
Thanks for the tip. Will do that later, or maybe just @Paget96 could do it,
but he's busy making the L Speed Mod application.

**Comment by Caio99BR** [comment]
The LS is wrong, you need put $ ($LS) or command will fail.
You need to put it on /tmp or /cache or /data, or directly put it on /system with right permissions.
At end exit, not recall script.

**Comment by msfjarvis** [comment]
This is deprecated. @Paget96 has built an application for L Speed and the script is now unmaintained.

**Comment by msfjarvis** [comment]
Though I'll merge in your pull request on my branch and maybe kickstart the
script again :wink:

On 13 February 2016 at 10:05, MSF Jarvis msfjarvis@gmail.com wrote:

> This is deprecated. @Paget96 has built an application for L Speed and the
> script is now unmaintained.

## 

MSF Jarvis
Junior Member
XDA-Developers.com(@ MSF Jarvis)

**Comment by Caio99BR** [comment]
Ok :D

**Pull request closed without merging**
